# Generated by Django 5.1.6 on 2025-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='photo',
            name='slot_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
