# Generated by Django 5.1.6 on 2025-03-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizer', '0004_camera_remove_photo_cameras_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.AddField(
            model_name='photo',
            name='cameras',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
    ]
