# Generated by Django 5.1.6 on 2025-03-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizer', '0005_delete_camera_photo_cameras_photo_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='digitization_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slot_number',
            field=models.IntegerField(unique=True),
        ),
    ]
